Add files via upload

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,13 +1,12 @@
-#!/bin/bash 
+#!/usr/bin/env bash 
 
 
---[[
-#      ▇▇▇                                       ▇▇▇               
-#      ▇▇        ▇                        ▇       ▇▇             
-#      ▇▇          ▇ @UU_IV   ▇         ▇▇            
-#      ▇▇             ▇             ▇             ▇▇         Dev :  MAHMOUD ABOELMAGD
-#      ▇▇                ▇       ▇                ▇▇    
-#      ▇▇                   ▇▇                    ▇▇     Source @UU_IV
+#                                  @ahmedyad200
+#   @ahmedyad200
+#     
+#                @ahmedyad200
+#                                @ahmedyad200
+#                                                            @ahmedyad200
 #---------------------------------------------------------------------
 cd $(cd $(dirname $0); pwd)
  
@@ -23,16 +22,16 @@ Version=`lsb_release -rs | cut -f1 -d"."`
 
 if [ "$Version" == "18" ];then
 echo -e "${GREEN}
-▇▇▇                                       ▇▇▇               
-▇▇        ▇                        ▇       ▇▇             
-▇▇          ▇ @UU_IV   ▇         ▇▇            
-▇▇             ▇             ▇             ▇▇        Dev : Mahmoud aboelmagd
-▇▇                ▇       ▇                ▇▇      
-▇▇                   ▇▇                    ▇▇     Source revor BY @UU_IV
+
+                    
+       ▇ @ahmedyad200   ▇                     ▄▇▄▄▄▄▄▇▄                            
+    ▄▇                                           ¦ Dev : @ahmedyad200
+ ▄▇ ¦ Dev : @ahmedyad200                    
+                                                               ¦ Source SELNDER BY @ahmedyad200
 ----------------------------------------------------------------------${CNIL}"
 echo -e "${RED}| للاسف لايمكنك تنصيب السورس ع نظام اوبنتو {${Version}} يجب ان يكون على اصدار  اقل مثلا  ${SMAY}14 او 16
 ${CNIL}";
-echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source revor 
+echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source SELNDER 
 ${CNIL}";
 exit;
 fi
@@ -42,7 +41,7 @@ if [ ! -f "./TG" ]; then
 echo -e "${RED}
 ¦
 ¦ CAUTION:${WHITB} Your Not Dwonload TG .
-¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source revor${CNIL} . \n
+¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source SELNDER${CNIL} . \n
 \n\n"
 chmod +x ./ins
 ./ins
@@ -65,16 +64,16 @@ sudo chmod +x ./TG
 
 if [ "$1" == "R" ] ; then
 while(true) do
-sudo killall -q ./TG
+killall -q ./TG
 sudo rm -fr ../.telegram-cli
-./TG -s ./inc/Run.lua --bot=$TOKEN
+./TG -s inc/Run.lua --bot=$TOKEN
 done
 else
 
-if ! screen -list | grep -q "FHAIWIH"; then
-screen -S FHAIWIH ./run R
+if ! screen -list | grep -q "SELNDER"; then
+screen -S SELNDER ./run R
 fi
-screen -X -S FHAIWIH kill
-screen -S FHAIWIH ./run R
+screen -S SELNDER -X kill
+screen -S SELNDER ./run R
 fi
 
